version: "3.7"
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Docker/nginx/Dockerfile
    networks:
      - internal
    ports:
      - "97:80"
    links:
      - php-fpm
    volumes:
      - db-data:/var/www/html

  php-fpm:
    container_name: app
    tty: true
    build:
      dockerfile: Docker/php/Dockerfile
    volumes:
      - .:/var/www
    networks:
      - internal

volumes:
  db-data:
    name: "my-app-data"

networks:
  internal:
    driver: bridge